### ISSUE TITLE
Please don’t abuse this!!!?

### ISSUE THREAD

**Issue by soheil** [dtinth/superwhite#2] opened 2023-06-19 15:49 UTC
This is your Github page and telling others not to abuse this? Get a grip dude.

<img width="1407" alt="image" src="https://github.com/dtinth/superwhite/assets/52513082/310240ff-5b4b-432b-8391-262263c40048">

**Comment by dtinth** [comment] 2023-06-19 16:26
thanks for noticing 😆 it says here in my bio:

![image](https://github.com/dtinth/superwhite/assets/193136/885dc49b-f91b-45b8-8234-18f814489de5)

closing this for now as the issue is not related to the project

**Closed as not planned by dtinth** 2023-06-19 16:26 UTC
